/* eslint-disable max-len */
const db = window.db;
// ==========================================
// SOLAR INPUT MODE
// ==========================================
window.calculationMode = "bill";

// Secure one-way cryptographic SHA-256 hashing engine
async function hashPin(pin) {
    const msgUint8 = new TextEncoder().encode(pin);
    const hashBuffer = await crypto.subtle.digest('SHA-256', msgUint8);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

// =====================================================================
// 1. PIN VERIFICATION PIPELINE & SERVER-SIDE CALL ENGINE
// =====================================================================
let currentPhone = null;         // Tracks active phone context for backend validation
let pinSuccessCallback = null;   // Stores redirect routine to fire on success
const LOCKOUT_KEY = "pin_lockout_time";
const ATTEMPTS_KEY = "pin_failed_attempts";

function triggerPinVerification(phone, unusedHashParam, callback) {
  // Check local device brute-force lockout status before opening UI elements
  const lockoutTime = localStorage.getItem(LOCKOUT_KEY);
  if (lockoutTime && Date.now() < parseInt(lockoutTime)) {
    const minutesLeft = Math.ceil((parseInt(lockoutTime) - Date.now()) / 60000);
    alert(`Security Alert: Too many failed login attempts. This device is locked out for another ${minutesLeft} minute(s).`);
    closeOTPModal();
    return;
  }

  // Set internal state context
  currentPhone = phone;
  pinSuccessCallback = callback;

  const phoneDisplayEl = document.getElementById("otpPhoneDisplay");
  if (phoneDisplayEl) {
    phoneDisplayEl.innerText = `Enter Security PIN for +91 ${phone}`;
  }

  const verifyBtn = document.getElementById("verifyOtpBtn");
  if (verifyBtn) {
    verifyBtn.innerText = "Verify PIN & Login";
  }

  document.querySelectorAll('.otp-digit').forEach(input => input.value = "");
  document.getElementById('otpModal').classList.remove('hidden');
}

function closeOTPModal() {
  document.getElementById('otpModal').classList.add('hidden');
  pinSuccessCallback = null;
  currentPhone = null;

  const leadSubmitBtn = document.querySelector("#leadPopup button");
  if (leadSubmitBtn) {
    leadSubmitBtn.disabled = false;
    leadSubmitBtn.innerText = "Show My Savings Report";
  }

  const signInBtn = document.getElementById("signInBtn");
  if (signInBtn) {
    signInBtn.disabled = false;
    signInBtn.innerText = "Continue";
  }
}

function resendOTP() {
  alert("Forgot your PIN? Please contact our support desk to manually re-verify your identity.");
}

async function verifyOTPCode() {
  const inputs = document.querySelectorAll('.otp-digit');
  const code = Array.from(inputs).map(i => i.value).join('');

  if (code.length < 4) {
    alert("Please enter your complete 4-digit security PIN.");
    return;
  }

  const btn = document.getElementById("verifyOtpBtn");
  btn.innerText = "Verifying Credentials...";
  btn.disabled = true;

  try {
    // 1. Encrypt the entered digits locally 
    const enteredHash = await hashPin(code);
    
    // 2. Initialize regionalized secure interface matching deployment architecture
    const verifyLeadPinFunction = firebase.app().functions('asia-south2').httpsCallable('verifyLeadPin');

    // 3. Dispatch the verification request out to the backend function
    const result = await verifyLeadPinFunction({ phone: currentPhone, enteredHash: enteredHash });
    
    if (result.data && result.data.success) {
      // Clear security counter thresholds upon valid response clearance
      localStorage.removeItem(ATTEMPTS_KEY);
      localStorage.removeItem(LOCKOUT_KEY);

      document.getElementById('otpModal').classList.add('hidden');
      
      const callback = pinSuccessCallback;
      const verifiedProfile = result.data.profile;
      const verifiedLeadId = result.data.leadId;

      // Reset application validation memory hooks
      pinSuccessCallback = null;
      currentPhone = null;
      
      // Fire the success loop passing through pure data structures generated by the server
      if (callback) callback(verifiedLeadId, verifiedProfile); 
    }
  } catch (serverError) {
    // Gracefully handle server rejections (e.g., incorrect code or active server-side locks)
    console.warn("Authentication channel transaction rejected:", serverError);
    alert(serverError.message); 
    
    btn.innerText = "Verify PIN & Login";
    btn.disabled = false;

    // Synchronize local UI state if backend flags a hard lockout sequence
    if (serverError.message.toLowerCase().includes("lock") || serverError.message.toLowerCase().includes("too many")) {
      closeOTPModal();
    }
  }
}

// =====================================================================
// 🔓 MODAL VISIBILITY TOGGLES
// =====================================================================
function openSignInModal(event) {
  if (event) event.preventDefault(); // Prevents the '#' from jumping the page to the top
  
  const signInModal = document.getElementById('signInModal');
  if (signInModal) {
    signInModal.classList.remove('hidden');
    
    // Autofocus the phone input for a cleaner UX
    const phoneInput = document.getElementById('signInPhone');
    if (phoneInput) phoneInput.focus();
  } else {
    console.error("⚠️ UI Error: Element with ID 'signInModal' was not found in the DOM.");
  }
}

function closeSignInModal(event) {
  if (event) event.preventDefault();
  
  const signInModal = document.getElementById('signInModal');
  if (signInModal) {
    signInModal.classList.add('hidden');
  }
  
  // Re-enable the primary call-to-action button if it was locked
  const btn = document.getElementById("signInBtn");
  if (btn) {
    btn.innerText = "Continue";
    btn.disabled = false;
  }
}

// =====================================================================
// 2. PIN-AUTHENTICATED USER SIGN-IN ROUTING
// =====================================================================
async function handleSignInSubmit() {
  const phoneRaw = document.getElementById('signInPhone').value.trim();
  const phone = normalizePhone(phoneRaw);
  const phoneRegex = /^[6-9]\d{9}$/;

  if (!phoneRegex.test(phone)) {
    alert("Please enter a valid 10-digit mobile number.");
    return;
  }

  // Pre-flight check device level lockout metrics
  const lockoutTime = localStorage.getItem(LOCKOUT_KEY);
  if (lockoutTime && Date.now() < parseInt(lockoutTime)) {
    const minutesLeft = Math.ceil((parseInt(lockoutTime) - Date.now()) / 60000);
    alert(`Access Denied: Locked out for another ${minutesLeft} minute(s).`);
    return;
  }

  const btn = document.getElementById("signInBtn");
  btn.innerText = "Checking Record...";
  btn.disabled = true;

  try {
    // Check if account target profile tracking maps correctly
    const snapshot = await db.collection("leads")
        .where("normalizedPhone", "==", phone)
        .orderBy("createdAt", "desc")
        .limit(1)
        .get();

    if (!snapshot.empty) {

    const existingLeadDoc = snapshot.docs[0];
    const existingData = existingLeadDoc.data();

    if (
        existingData.consentWithdrawn === true ||
        existingData.processingDisabled === true ||
        existingData.loginDisabled === true ||
        existingData.stage === "CONSENT_WITHDRAWN"
    ) {

        alert(
          "Your previous request was deleted after consent withdrawal. Please start a new solar assessment."
        );

        btn.innerText = "Continue";
        btn.disabled = false;

        return;
    }

    if (!existingData.pinHash) {

    localStorage.setItem("leadId", existingLeadDoc.id);
    localStorage.setItem("leadCode", existingData.leadCode || "");
    localStorage.setItem("leadName", existingData.name || "Homeowner");
    localStorage.setItem("leadPhone", existingData.phone || phone);
    localStorage.setItem("leadStage", existingData.stage || "INITIAL");
    localStorage.setItem("state", existingData.state || "UP");
    localStorage.setItem("bill", existingData.bill || 1500);

            const createSession =
  firebase
    .app()
    .functions("asia-south2")
    .httpsCallable(
      "createLeadSession"
    );

const sessionResult =
  await createSession({
    leadId: existingLeadDoc.id
  });

localStorage.setItem(
  "sessionToken",
  sessionResult.data.sessionToken
);
            
    window.location.href = `results.html`;
    return;
}
        

    // ====================================
    // DPDP CONSENT WITHDRAWAL PROTECTION
    // ====================================

    

    document.getElementById('signInModal')?.classList.add('hidden');

    // Fire PIN entry screen
    triggerPinVerification(phone, null, async (serverLeadId, serverProfile) => {
            
            // Hydrate local cache stores strictly from backend returned safe fields
            localStorage.setItem("leadId", serverLeadId);
            localStorage.setItem("leadCode", serverProfile.leadCode || "");
            localStorage.setItem("state", serverProfile.state || "");
            localStorage.setItem("leadStage", serverProfile.stage || "INITIAL");
            localStorage.setItem("leadName", serverProfile.name || "Homeowner");
            localStorage.setItem("leadPhone", serverProfile.phone || phone);
            localStorage.setItem("leadCity", serverProfile.city || "");
            localStorage.setItem("bill", serverProfile.bill || "1500");
        // Restore original calculation mode
            localStorage.setItem(
              "calculationMode",
              serverProfile.calculationMode || "bill"
            );
            
            if (
              serverProfile.calculationMode === "kw" &&
              serverProfile.systemSizeKw
            ) {
              localStorage.setItem(
                "selectedKw",
                serverProfile.systemSizeKw
              );
            } else {
              localStorage.removeItem("selectedKw");
            }

        const createSession =
firebase
  .app()
  .functions("asia-south2")
  .httpsCallable(
    "createLeadSession"
  );

const sessionResult =
await createSession({
  leadId: serverLeadId
});

localStorage.setItem(
  "sessionToken",
  sessionResult.data.sessionToken
);
        
            // Complete user session handoff 
            window.location.href =
`results.html?bill=${serverProfile.bill}` +
`&systemSizeKw=${serverProfile.systemSizeKw || ""}` +
`&state=${serverProfile.state}` +
`&name=${encodeURIComponent(serverProfile.name)}` +
`&phone=${encodeURIComponent(serverProfile.phone)}` +
`&city=${encodeURIComponent(serverProfile.city || "")}`;

        });
    } else {
        alert("No account found for this number. Please calculate your savings first to generate a report.");
        btn.innerText = "Continue";
        btn.disabled = false;
    }
  } catch (e) {
     console.error("Sign-in infrastructure lookup exception:", e);
     alert("Unable to complete login sequence. Please try again.");
     btn.innerText = "Continue";
     btn.disabled = false;
  }
}

// ==========================================
// INPUT MODE SWITCHER
// ==========================================
function switchCalculationMode(mode) {

  window.calculationMode = mode;

  const billContainer =
    document.getElementById("billInputContainer");

  const kwContainer =
    document.getElementById("kwInputContainer");

  const billBtn =
    document.getElementById("billModeBtn");

  const kwBtn =
    document.getElementById("kwModeBtn");

  if (mode === "bill") {

    billContainer.classList.remove("hidden");
    kwContainer.classList.add("hidden");

    billBtn.classList.add("bg-white", "text-slate-900");
    billBtn.classList.remove("text-white");

    kwBtn.classList.remove("bg-white", "text-slate-900");
    kwBtn.classList.add("text-white");

  } else {

    kwContainer.classList.remove("hidden");
    billContainer.classList.add("hidden");

    kwBtn.classList.add("bg-white", "text-slate-900");
    kwBtn.classList.remove("text-white");

    billBtn.classList.remove("bg-white", "text-slate-900");
    billBtn.classList.add("text-white");
  }
}

// ==========================================
// 3. HELPERS & UTILITIES
// ==========================================

function getLeadType(bill) {
  if (bill >= 3000) return "Hot";
  if (bill >= 1500) return "Warm";
  return "Basic";
}

function generateLeadCode(phone) {
  const d = new Date();
  const date = d.toISOString().slice(0, 10).replace(/-/g, "");
  const last4 = phone.slice(-4);
  const rand = Math.random().toString(36).slice(2, 6).toUpperCase();
  return `SOL-${date}-${last4}-${rand}`;
}

function normalizePhone(phone) {
  phone = phone.replace(/\D/g, "");
  if (phone.startsWith("91") && phone.length === 12) phone = phone.slice(2);
  if (phone.startsWith("0") && phone.length === 11) phone = phone.slice(1);
  return phone;
}

function showError(inputId, errorId, message) {
  const errorEl = document.getElementById(errorId);
  const inputEl = document.getElementById(inputId);
  if (errorEl) errorEl.innerText = message;
  if (inputEl) {
    inputEl.style.borderColor = "#ef4444"; 
    inputEl.classList.add("bg-red-50");
  }
}

function clearError(inputId, errorId) {
  const errorEl = document.getElementById(errorId);
  const inputEl = document.getElementById(inputId);
  if (errorEl) errorEl.innerText = "";
  if (inputEl) {
    inputEl.style.borderColor = ""; 
    inputEl.classList.remove("bg-red-50");
  }
}

function getStateFromPin(pin) {
  if (!pin || pin.length < 2) return "DL";
  const prefix = parseInt(pin.substring(0, 2));
  if (prefix === 11) return "DL";
  if (prefix >= 12 && prefix <= 13) return "HR";
  if (prefix >= 14 && prefix <= 16) return "PB";
  if (prefix === 17) return "HP";
  if (prefix >= 18 && prefix <= 19) return "JK";
  if (prefix >= 20 && prefix <= 23) return "UP";
  if (prefix >= 24 && prefix <= 28) return "UK"; 
  if (prefix >= 30 && prefix <= 34) return "RJ";
  if (prefix >= 36 && prefix <= 39) return "GJ";
  if (prefix >= 40 && prefix <= 44) return "MH";
  if (prefix >= 45 && prefix <= 48) return "MP";
  if (prefix === 49) return "CG";
  if (prefix === 50) return "TS";
  if (prefix >= 51 && prefix <= 53) return "AP";
  if (prefix >= 56 && prefix <= 59) return "KA";
  if (prefix >= 60 && prefix <= 64) return "TN";
  if (prefix >= 67 && prefix <= 69) return "KL";
  if (prefix >= 70 && prefix <= 74) return "WB";
  if (prefix >= 75 && prefix <= 77) return "OR";
  if (prefix === 78) return "AS";
  if (prefix === 79) return "AR"; 
  if (prefix >= 80 && prefix <= 85) return "BR";
  return "DL";
}

// ==========================================
// 4. UNIFIED VALIDATION
// ==========================================
function validateForm(prefix, name, email, phone, city) {
  let isValid = true;
  
  const nameRegex = /^[A-Za-z\s]+$/; 
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  const phoneRegex = /^[6-9]\d{9}$/;

  const fields = {
    name: { input: prefix + 'Name', error: prefix === 'cons'? 'consNameError' : 'nameError' },
    email: { input: prefix + 'Email', error: prefix === 'cons'? 'consEmailError' : 'emailError' },
    phone: { input: prefix + 'Phone', error: prefix === 'cons'? 'consPhoneError' : 'phoneError' }
  };
  if (prefix === 'cons') {
    fields.city = { input: 'consCity', error: 'consCityError' };
  }

  Object.values(fields).forEach(f => {
    const el = document.getElementById(f.input);
    if (el) clearError(f.input, f.error);
  });

  if (prefix === 'lead' && name.trim().length === 0) {
    // Optional - skip error checks
  } else if (!nameRegex.test(name) || name.trim().length < 2) {
    showError(fields.name.input, fields.name.error, "Enter valid name (letters only)");
    isValid = false;
  }

  if (email.length > 0 &&!emailRegex.test(email)) {
    showError(fields.email.input, fields.email.error, "Please enter a valid email format");
    isValid = false;
  }
  
  const normalizedPhone = normalizePhone(phone);
  if (!phoneRegex.test(normalizedPhone)) {
    showError(fields.phone.input, fields.phone.error, "Enter valid 10-digit mobile");
    isValid = false;
  }

  if (prefix === 'cons') {
    if (!city || city.length < 2) {
      showError(fields.city.input, fields.city.error, "Enter your city");
      isValid = false;
    }
  }

  return { isValid, normalizedPhone };
}

// ==========================================
// 5. CORE FUNCTIONALITY & SUBMISSIONS
// ==========================================
function handleHeroCalculate() {

  const pincodeInput =
    document.getElementById("pincodeInput");

  const pincodeValue =
    pincodeInput?.value?.trim();

  clearError("billInput", "billError");
  clearError("pincodeInput", "pincodeError");

  let isValid = true;
  let calculatedBill = 0;

  // =========================
  // BILL MODE
  // =========================

  if (window.calculationMode === "bill") {

    const billInput =
      document.getElementById("billInput");

    const billValue =
      billInput?.value;

    const bill =
      parseFloat(billValue);

    if (!billValue || isNaN(bill) || bill < 500) {
      showError(
        "billInput",
        "billError",
        "Min. bill ₹500 required"
      );
      isValid = false;
    }

    calculatedBill = bill;
    localStorage.setItem("calculationMode", "bill");
    localStorage.removeItem("selectedKw");
  }

  // =========================
  // KW MODE
  // =========================

  else {

    const kwInput =
      document.getElementById("systemSizeInput");

    const kw =
      parseFloat(kwInput?.value || 3);

    if (!kw || kw <= 0) {

      alert("Please select a valid system size.");

      return;
    }

    // Residential rooftop approximation
calculatedBill = Math.round(kw * 900);

    localStorage.setItem("selectedKw", kw);
    localStorage.setItem("calculationMode", "kw");
  }

  // =========================
  // PINCODE VALIDATION
  // =========================

  const pincodeRegex = /^[1-9][0-9]{5}$/;

  if (!pincodeValue || !pincodeRegex.test(pincodeValue)) {

    showError(
      "pincodeInput",
      "pincodeError",
      "Enter valid 6-digit PIN code"
    );

    isValid = false;
  }

  if (isValid) {

    const resolvedState =
      getStateFromPin(pincodeValue);

    localStorage.setItem(
      "pincode",
      pincodeValue
    );

    localStorage.setItem(
      "state",
      resolvedState
    );

    localStorage.setItem(
      "bill",
      calculatedBill
    );

    window.currentBill =
      calculatedBill;

    document
      .getElementById("leadPopup")
      .classList.remove("hidden");
  }
}

async function handleConsultationSubmit() {
  const name = document.getElementById('consName').value.trim();
  const email = document.getElementById('consEmail').value.trim();
  const phoneInput = document.getElementById('consPhone').value.trim();
  const city = document.getElementById('consCity').value.trim();

  const submitBtn = document.getElementById("consSubmitBtn");
  const validation = validateForm("cons", name, email, phoneInput, city);

  if (!validation.isValid) return;

  submitBtn.disabled = true;
  submitBtn.innerText = "Processing...";

  try {
    await db.collection("consultations").add({
      name: name,
      email: email, 
      phone: validation.normalizedPhone,
      city: city,
      source: "Free Consultation Popup",
      status: "New",
      createdAt: firebase.firestore.FieldValue.serverTimestamp()
    });

    document.getElementById("consFormContainer").classList.add("hidden");
    document.getElementById("consSuccessMsg").classList.remove("hidden");
    setTimeout(closeConsultation, 3000);

  } catch (e) {
    console.error("Error:", e);
    alert("Submission failed. Please try again.");
  } finally {
    submitBtn.disabled = false;
    submitBtn.innerText = "Request Call Back";
  }
}

async function submitLeadAndContinue(event) {
  if (event) event.preventDefault();
  const submitBtn = document.querySelector("#leadPopup button");
  
  const name = document.getElementById("leadName").value.trim();
  const email = document.getElementById("leadEmail").value.trim();
  const phoneRaw = document.getElementById("leadPhone").value.trim();
  const bill = localStorage.getItem("bill") || window.currentBill;
  const pincode = localStorage.getItem("pincode") || "";
  const city = ""; 

  const validation = validateForm("lead", name, email, phoneRaw, city);
  if (!validation.isValid) return;

  const phone = validation.normalizedPhone;
  
  const consentCheckbox = document.getElementById("leadConsentCheckbox");
  if (!consentCheckbox || !consentCheckbox.checked) {
    alert("Please accept the privacy policy consent to view your savings report.");
    return;
  }

  submitBtn.disabled = true;
  submitBtn.innerText = "Processing Pipeline...";

  try {
    // Check if the record already exists directly without an intervening OTP block
    const snapshot = await db.collection("leads")
        .where("normalizedPhone", "==", phone)
        .orderBy("createdAt", "desc")
        .limit(1)
        .get();
  
    if (!snapshot.empty) {
        const existingLeadDoc = snapshot.docs[0];

    const existingData = existingLeadDoc.data();
    // ====================================
// DPDP CONSENT WITHDRAWAL PROTECTION
// ====================================

if (
    existingData.consentWithdrawn === true ||
    existingData.processingDisabled === true ||
    existingData.loginDisabled === true ||
    existingData.stage === "CONSENT_WITHDRAWN"
) {

    console.log(
        "Withdrawn lead detected. Creating fresh lead."
    );

} else {
    
        // --------------------------------
    // USER HAS NO PIN YET
    // --------------------------------

    if (!existingData.pinHash) {

        localStorage.setItem(
            "leadId",
            existingLeadDoc.id
        );

        localStorage.setItem(
            "leadCode",
            existingData.leadCode || ""
        );

        localStorage.setItem(
            "leadName",
            existingData.name || "Homeowner"
        );

        localStorage.setItem(
            "leadPhone",
            existingData.phone || phone
        );

        localStorage.setItem(
            "leadStage",
            existingData.stage || "INITIAL"
        );

        localStorage.setItem(
            "state",
            existingData.state || "UP"
        );

        localStorage.setItem(
            "bill",
            existingData.bill || 1500
        );

        localStorage.setItem(
  "leadCity",
  existingData.city || ""
);

localStorage.setItem(
  "calculationMode",
  existingData.calculationMode || "bill"
);

if (
  existingData.calculationMode === "kw" &&
  existingData.systemSizeKw
) {
  localStorage.setItem(
    "selectedKw",
    existingData.systemSizeKw
  );
}
        

        const createSession =
  firebase
    .app()
    .functions("asia-south2")
    .httpsCallable(
      "createLeadSession"
    );

const sessionResult =
  await createSession({
    leadId: existingLeadDoc.id
  });

localStorage.setItem(
  "sessionToken",
  sessionResult.data.sessionToken
);
        console.log(
  "inside submitLeadAndContinue SESSION RESULT",
  sessionResult
);

console.log(
  "inside submitLeadAndContinue SESSION TOKEN",
  sessionResult?.data?.sessionToken
);
        window.location.href =
`results.html?bill=${existingData.bill || ""}` +
`&systemSizeKw=${existingData.systemSizeKw || ""}` +
`&state=${existingData.state || "UP"}` +
`&name=${encodeURIComponent(existingData.name || "Homeowner")}` +
`&phone=${encodeURIComponent(existingData.phone || phone)}` +
`&city=${encodeURIComponent(existingData.city || "")}`;

        return;
    }

    // --------------------------------
    // USER HAS PIN
    // --------------------------------

  submitBtn.disabled = false;
  submitBtn.innerText =
    "Show My Savings Report";

  document
    .getElementById("leadPopup")
    ?.classList.add("hidden");

  triggerPinVerification(
    phone,
    null,
    async (
      serverLeadId,
      serverProfile
    ) => {

      const createSession =
        firebase
          .app()
          .functions("asia-south2")
          .httpsCallable(
            "createLeadSession"
          );

      const sessionResult =
        await createSession({
          leadId: serverLeadId
        });

      localStorage.setItem(
        "sessionToken",
        sessionResult.data.sessionToken
      );

      localStorage.setItem(
        "leadId",
        serverLeadId
      );

    localStorage.setItem(
        "leadCode",
        serverProfile.leadCode || ""
        );
        
    localStorage.setItem(
        "leadName",
        serverProfile.name || "Homeowner"
        );

        localStorage.setItem(
                "leadPhone",
                serverProfile.phone || phone
            );
        
    localStorage.setItem(
        "leadStage",
        serverProfile.stage || "INITIAL"
        );

        localStorage.setItem(
          "state",
          serverProfile.state || "UP"
        );

    localStorage.setItem(
      "bill",
      serverProfile.bill || 1500
    );
    
    localStorage.setItem(
      "leadCity",
      serverProfile.city || ""
    );
    
    localStorage.setItem(
      "calculationMode",
      serverProfile.calculationMode || "bill"
    );
    
    if (
      serverProfile.calculationMode === "kw" &&
      serverProfile.systemSizeKw
    ) {
      localStorage.setItem(
        "selectedKw",
        serverProfile.systemSizeKw
      );
    }

        console.log(
  "USER HAS PIN SESSION RESULT",
  sessionResult
);

console.log(
  "USER HAS PIN SESSION TOKEN",
  sessionResult?.data?.sessionToken
);
        
      window.location.href =
`results.html?bill=${serverProfile.bill || ""}` +
`&systemSizeKw=${serverProfile.systemSizeKw || ""}` +
`&state=${serverProfile.state || "UP"}` +
`&name=${encodeURIComponent(serverProfile.name || "Homeowner")}` +
`&phone=${encodeURIComponent(serverProfile.phone || phone)}` +
`&city=${encodeURIComponent(serverProfile.city || "")}`;
    }
  );

  return;
}
}
    // Process new database transaction entry records
    const leadType = getLeadType(parseFloat(bill));
    const leadCode = generateLeadCode(phone);
    const resolvedState = getStateFromPin(pincode);
    const resolvedCity =
    window.verifiedCity ||
    localStorage.getItem("verifiedCity") ||
    "Not Provided";

    const docRef = await db.collection("leads").add({
      name: name || "Homeowner", 
      email: email || "",
      phone,
      normalizedPhone: phone,
      city: resolvedCity,
      pincode: pincode,
      state: resolvedState,
      bill: parseFloat(bill),
      systemSizeKw: localStorage.getItem("selectedKw") || "",
      calculationMode: localStorage.getItem("calculationMode") || "bill",
      leadCode,
      customerId: phone,
      leadType,
      status: "New",
      stage: "initial",
      leadSource: "Website",
      assignedTo: "",
      assignedInstallerId: "",
      sharedWithInstaller: false,
      paymentStatus: "PENDING",
      lastContactedAt: null,
      nextFollowupAt: null,
      lastUpdatedBy: "",
      notes: [],
      isTestLead: false,
      consentGiven: true,
      consentTimestamp: firebase.firestore.FieldValue.serverTimestamp(),
      consentVersion: "1.0-rules-2025",
      createdAt: firebase.firestore.FieldValue.serverTimestamp(),
      updatedAt: firebase.firestore.FieldValue.serverTimestamp()
    });
    
    localStorage.setItem("leadId", docRef.id);
    localStorage.setItem("leadCode", leadCode); 
    localStorage.setItem("state", resolvedState);
    localStorage.setItem("leadName", name || "Homeowner");
    localStorage.setItem("leadPhone", phone);
    localStorage.setItem("leadCity", resolvedCity);
    localStorage.setItem("leadBill", bill);
    
    const selectedKw =
  localStorage.getItem("selectedKw") || "";

window.location.href =
`results.html?bill=${bill}` +
`&systemSizeKw=${selectedKw}` +
`&state=${resolvedState}` +
`&name=${encodeURIComponent(name || "Homeowner")}` +
`&email=${encodeURIComponent(email)}` +
`&phone=${encodeURIComponent(phone)}` +
`&city=${encodeURIComponent(resolvedCity)}`;

  } catch (error) {
    console.error("Firestore Transaction Error:", error);
    submitBtn.disabled = false;
    submitBtn.innerText = "Show My Savings Report";
    alert("Submission failed. Please try again.");
  }
}

// ==========================================
// 6. WHATSAPP & UI HELPERS
// ==========================================
function scrollToTop() {
  window.scrollTo({
    top: 0,
    behavior: "smooth"
  });
  
  // Optional: Set focus to bill input for instant typing accessibility
  setTimeout(() => {
    document.getElementById("billInput")?.focus();
  }, 400);
}

function openWhatsAppChat(customMessage = "") {
  const defaultMessage = "Hi, I’m interested in rooftop solar. Can your solar advisor help me?";
  const message = customMessage || defaultMessage;
  window.open(`https://wa.me/61404166347?text=${encodeURIComponent(message)}`, "_blank");
}

function openConsultation() {
  document.getElementById('consultationPopup').classList.remove('hidden');
}

function closeConsultation() {
  document.getElementById('consultationPopup').classList.add('hidden');
  setTimeout(() => {
    document.getElementById("consFormContainer").classList.remove("hidden");
    document.getElementById("consSuccessMsg").classList.add("hidden");
    ['consName', 'consEmail', 'consPhone', 'consCity'].forEach(id => {
      document.getElementById(id).value = "";
    });
  }, 500);
}

// ==========================================
// 7. LIFECYCLE & EVENT LISTENERS
// ==========================================
document.addEventListener("DOMContentLoaded", function () {
  document.getElementById("leadPopup")?.classList.add("hidden");
  document.getElementById("consultationPopup")?.classList.add("hidden");
switchCalculationMode("bill");
  // Setup PIN Digit Input Auto-Advance behavior
  const otpInputs = document.querySelectorAll('.otp-digit');
  otpInputs.forEach((input, index) => {
    input.addEventListener('input', (e) => {
      if (e.target.value.length === 1 && index < otpInputs.length - 1) {
        otpInputs[index + 1].focus();
      }
    });
    input.addEventListener('keydown', (e) => {
      if (e.key === 'Backspace' && !e.target.value && index > 0) {
        otpInputs[index - 1].focus();
      }
      if (e.key === 'Enter') {
        verifyOTPCode();
      }
    });
  });
});

// =====================================================================
// 🚀 INJECTED LOOKUP PIPELINE FOR THE HOMEPAGE FIELD (UPDATED FIXES)
// =====================================================================
document.addEventListener("DOMContentLoaded", () => {
  // 1. Corrected to target 'pincodeInput' matching your index.html layout
  const pinInputField = document.getElementById("pincodeInput"); 
  
  if (!pinInputField) return;

  pinInputField.addEventListener("input", async (e) => {
    let pinValue = e.target.value.replace(/\D/g, ""); 
    e.target.value = pinValue; 
    
    if (pinValue.length === 6) {
      const locationData = await lookupPincodeData(pinValue);
      const feedbackContainer = document.getElementById("locationFeedbackMsg");

      if (locationData) {
        const [district, fullStateName] = locationData;
        const stateCode = normalizeStateToCode(fullStateName) || "UP";

        // Save globally and locally across runtime processes
        window.verifiedCity = district;
        window.verifiedState = stateCode;
        localStorage.setItem("verifiedCity", district);
        localStorage.setItem("verifiedState", stateCode);
        localStorage.setItem("state", stateCode);
        localStorage.setItem("pincode", pinValue);

        if (feedbackContainer) {
          feedbackContainer.className = "text-xs mt-1 text-green-300 font-medium text-left ml-1";
          feedbackContainer.innerText = `📍 Verified Area: ${district}, ${fullStateName}`;
        }
      } else {
        if (feedbackContainer) {
          feedbackContainer.className = "text-xs mt-1 text-amber-300 font-medium text-left ml-1";
          feedbackContainer.innerText = "⚠️ Custom location mapping enabled.";
        }
      }
    }
  });
});

// 2. Gracefully intercept the old hardcoded state range function synchronously
const originalGetStateFromPin = getStateFromPin;
getStateFromPin = function(pin) {
  const cachedState = window.verifiedState || localStorage.getItem("verifiedState");
  if (cachedState) return cachedState;
  return originalGetStateFromPin(pin);
};

// 3. Database Payload Interceptor: Overrides the Firestore layer to catch 
// data additions and inject verified location models over hardcoded placeholders
if (window.db) {
  const originalCollection = window.db.collection;
  window.db.collection = function(name) {
    const collectionRef = originalCollection.apply(this, arguments);
    if (name === "leads") {
      const originalAdd = collectionRef.add;
      collectionRef.add = function(data) {
        const trueCity = window.verifiedCity || localStorage.getItem("verifiedCity");
        const trueState = window.verifiedState || localStorage.getItem("verifiedState");
        if (trueCity) data.city = trueCity;
        if (trueState) data.state = trueState;
        return originalAdd.apply(this, arguments);
      };
    }
    return collectionRef;
  };
}
